#spring.application.name=weshopify-user-management-service

server:
  port: ${USER_SVC_PORT:5014}
  
spring:
  application:
    name: ${USER_SVC_NAME:user-management-service}
 
# swagger-ui custom path
springdoc:
  swagger-ui:
      path: ${USER_SWAGGER_PATH:/swagger-ui.html}


iam-server:
  base-url: https://${WSO2_SERVER_HOST_NAME:host.docker.internal:9443}/scim2
  role-api: /Roles
  user-api: /Users
  user-name: ${WSO2_SERVER_USER_NAME:admin}
  password: ${WSO2_SERVER_USER_PASSWORD:admin}
  role-api-schema: "urn:ietf:params:scim:schemas:core:2.0:Role"
  
  
