spring:
  application:
         name: weshopify-category-service
  datasource:
         username: '${CATEGORIES_DB_USER:root}'
         password: '${CATEGORIES_DB_PASSWORD:manager}'
         url: 'jdbc:${CATEGORIES_DB_TYPE:mysql}://${CATEGORIES_DB_HOST:localhost}:${CATEGORIES_DB_PORT:3306}/${CATEGORIES_DB_SCHEMA:weshopify_categories_service}'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true 
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
  data:
     redis:
      #host: 127.0.0.1
      host: ${REDIS_SERVER_HOST:host.docker.internal}
      port: 6379
      password: Redis123$
      
eureka:
  client:
    service-url:
      #defaultZone: http://${SERVICE_REGISTRY_HOST:localhost}:${SERVICE_REGISTRY_PORT:8761}/eureka/
      defaultZone: http://${SERVICE_REGISTRY_HOST:host.docker.internal}:${SERVICE_REGISTRY_PORT:8761}/eureka/
  instance:
    #hostname: ${SERVICE_REGISTRY_HOST:localhost}
    hostname: ${SERVICE_REGISTRY_HOST:host.docker.internal}
    
axon:
  axonserver:
    servers: ${AXON_SERVER_HOST:localhost}:${AXON_SERVER_PORT:8024}
    #servers: ${AXON_SERVER_HOST:host.docker.internal}:${AXON_SERVER_PORT:8024}
      
server:
  port: 5016
